### ISSUE TITLE
having issue with location 

### ISSUE THREAD

**Issue by tjw0lf** [kasramp/UbuntuIndicatorWeather#24] opened 2017-01-13 02:17 UTC
I put my lat and long in but its coming up with weird name not Buffalo NY. How do i fix

**Comment by briari** [comment] 2017-01-15 17:50
I am having the same issue and the location changes intermittently to a different strange location - not Atlanta, GA.

**Comment by kasramp** [comment] 2017-01-16 15:32
If the location sometimes shows wrong (random occasion and not all the time), then that's a known API problem and I am trying to fix it, though the weather report is accurate, just location shows wrong due to race condition. But if all the times the location is displaying something weird even if you set your lat and lon properly, I highly suspect that's coming from Open Weather Map since it translates lat and lon to address. There is a third scenario in which location detection is set to automatic and inaccuracy of the location is mostly due to location of the service provider and inaccuracy of Ip-api.com service. If can provide more details such as what lat, lon did you set and what was the result of the location and what is the expected location to help me to troubleshoot the problem easier.

**Comment by kasramp** [comment] 2017-01-30 01:58
Hi @tjw0lf @briari, I have fixed the API problem and it's already deployed. It is expected to fix the problem of constantly changing the location. You don't need to update your app, as the changes are done on the backend. Please observe and do let me know the issue is resolved or it's still persisting. 
For now I close the issue feel free to reopen it.

**Closed by kasramp** 2017-01-30 01:58 UTC
Labels: bug
