### ISSUE TITLE
ubuntu 16.10 applet don't start

### ISSUE THREAD

**Issue by lodgnewt** [kasramp/UbuntuIndicatorWeather#19] opened 2016-10-20 15:53 UTC
please fix your great indicator. thanks.
indicator don't start on fresh install ubuntu 16.10

**Comment by kasramp** [comment] 2016-10-23 14:42
To understand the problem clearly, run `indicator-weather` in your command line and copy/paste the output here, so I can know what's the exact problem you are facing. Thanks

**Comment by andyturn** [comment] 2016-11-02 22:46
I am having an issue where the indicator will not start on ubuntu 16.10 as well.  Below is the output you requested.


/usr/bin/indicator-weather:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appIndicator
Traceback (most recent call last):
  File "/usr/bin/indicator-weather", line 143, in <module>
    indicator = WeatherIndicator()
  File "/usr/bin/indicator-weather", line 62, in __init__
    self.configuration = Configuration()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 29, in __init__
    self.ini_start_up = self.__create_start_up_script_if_not_exist()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 46, in __create_start_up_script_if_not_exist
    return self.__create_default_start_up_script_and_save_to_disk()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 98, in __create_default_start_up_script_and_save_to_disk
    self.__save_ini_start_up_script_to_disk(config)
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 68, in __save_ini_start_up_script_to_disk
    with open(self.start_up_file_name, 'w') as config_file:
IOError: [Errno 2] No such file or directory: '/home/andyt/.config/autostart/indicator-weather.desktop'

**Comment by kasramp** [comment] 2016-11-17 15:14
Thanks @andyturn for the log, I will checking the issue

**Comment by kasramp** [comment] 2016-11-19 03:58
Fixed in 0.8.1

**Closed by kasramp** 2016-11-19 03:58 UTC
Labels: bug

**Comment by andyturn** [comment] 2016-11-19 21:41
i have reinstalled and this is the error i am receiving now when trying to run.

indicator-weather
/usr/bin/indicator-weather:28: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appIndicator
Traceback (most recent call last):
  File "/usr/bin/indicator-weather", line 144, in <module>
    indicator = WeatherIndicator()
  File "/usr/bin/indicator-weather", line 63, in __init__
    self.configuration = Configuration()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 29, in __init__
    self.ini_start_up = self.__create_start_up_script_if_not_exist()
  File "/usr/lib/ubuntu-indicator-weather/configuration.py", line 49, in __create_start_up_script_if_not_exist
    if exc.errno != errno.EEXIST:
NameError: global name 'errno' is not defined

**Comment by kasramp** [comment] 2016-11-19 23:51
Well that's very odd. @andyturn what version of Python are you using?
What you can do for now is to edit `/usr/lib/ubuntu-indicato-weather/configuration.py` file and add this line on top of the file `import errno`, so at least we can get more details about the error.
I think there would be still an error because from my understanding the startup file cannot be created on your machine, that's why an exception is raised, not sure what's the exact reason, maybe it's something related to permission. I hope adding that line provides more insight regarding the error so I can fix it more precisely. After modifying the code if you received another error message, please paste it here. 
I have checked on Ubuntu 16.10 but cannot reproduce the error 😞
