### ISSUE TITLE
Indicator Weather does not display temp nor any other data

### ISSUE THREAD

**Issue by Brett-Holmes** [kasramp/UbuntuIndicatorWeather#43] opened 2017-04-28 16:06 UTC
Whenever I open indicator-weather the temperature does not populate, nor does the information in the dropdown. I've installed all of the needed dependencies as well as restarting the machine, and installing and uninstalling. I cannot find a solution. Screenshots have been attached.
![indicator-weather](https://cloud.githubusercontent.com/assets/9272072/25537087/17619572-2c0b-11e7-82bd-943c2ee71164.png)
![indicator-weather-dropdown-cropped](https://cloud.githubusercontent.com/assets/9272072/25537092/1cba1c42-2c0b-11e7-8ff0-6a5f71324d81.png)

**Comment by Brett-Holmes** [comment] 2017-04-28 17:11
The temperature now shows, but it's not updating regularly. The weather won't change until the indicator is quit and opened again.

**Comment by kasramp** [comment] 2017-04-28 23:56
@Brett-Holmes - since few days ago, have been facing some issues that cause the container to crash. That's why often the service is interrupted. I am looking into the problem to solve it.
The problem is from the in-house weather service not the indicator. Once it's resolved, the problem should go away.

**Comment by kasramp** [comment] 2017-05-13 03:02
@Brett-Holmes - I've fixed the problem, so I am closing the ticket. Let me know if you face any further problem.

**Closed by kasramp** 2017-05-13 03:02 UTC
Labels: bug
